# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 911f11972013149197bc26e39392384c3325be01bb9d702b23b22cb349e37f860dacdf0a2d3bf83fa1fba2ea082d995b6a74e913916f2ec07d09a3f2810e986a

test:
  secret_key_base: 00eadbefa328130204ad5e43417dbaa8ba48986d7c0d276299fd7cd961a7db09dc18870dae832f6e90c23cee1164a803cd8af85db905d4118f18c63f6d9b8752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
